import { Inter } from 'next/font/google'
import './globals.css'
import { ResultProvider } from '@/Context/ResultContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MBG-Quiz App',
  description: 'Generated by MBG',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ResultProvider>
          {children}
        </ResultProvider>
      </body>
    </html>
  )
}
